print(1)
print(True and True)
print(True)
print(2)
print(False and True)
print(False)
print(3)
print(1 == 1 and 2 == 1)
print(False)
print(4)
print("test" == "test")
print(True)
print(5)
print(1 == 1 or 2 != 1)
print(True)
print(6)
print(True and 1 == 1)
print(True)
print(7)
print("test" == "testing")
print(False)
print(8)
print(1 != 0 and 2 == 1)
print(False)
print(9)
print("test" != "testing")
print(True)
print(10)
print("test" == 1)
print(False)
print(11)
print(not (True and False))
print(True)
print(12)
print(not (1 == 1 and 0 != 1))
print(False)
print(13)
print(not (10 == 1 or 1000 == 1000))
print(False)
print(14)
print(not (1 != 10 or 3 == 4))
print(False)
print(15)
print(not ("testing" == "testing" and "Zed" == "Cool Guy"))
print(True)
print(16)
print(1 == 1 and (not ("testing" == 1 or 1 ==0)))
print(True)
print(17)
print("chunky" == "bacon" and (not ( 3 == 4 or 3 == 3)))
print(False)
print(18)
print(3 == 3 and (not("testing" == "testing" or "Python" == "Fun")))
print(False)
print(19)
print(False and 0 != 0)
print(False)
print(20)
print(True or 1 == 1)
print(True)
